version: '3'
services:
  client-prod:
    build:
      context: ./client
      dockerfile: Dockerfile-production
    ports:
      - '80:80'
    depends_on:
      - server-prod
    volumes_from:
      - server-prod:ro

  server-prod:
    build:
      context: ./server
      dockerfile: Dockerfile-production
    environment:
      NODE_ENV: production
    depends_on:
      - db-prod
      # - mongo-prod
    volumes:
      - /var/www/html/images:/var/www/html/images

  db-prod:
    image: postgres:13-alpine
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=todo-prod

  # mongo-prod:
  #   image: mongo:4.4-focal
  #   environment:
  #     - MONGO_DATA_DIR=/data/db
  #     - MONGO_LOG_DIR=/dev/null
  #   volumes:
  #     - ./data/db:/data/db
  #   command: mongod --smallfiles --logpath=/dev/null

volumes:
  server-prod:
  nginx-server-prod:
