version: '3'
services:
  front-react:
    build:
      context: ./client
    environment:
      NODE_ENV: development
    depends_on:
      - server-dev
    volumes:
      - ./client:/client
      - /client/node_modules
    ports:
      - '5173:5173'

  server-dev:
    build:
      context: ./server
    restart: on-failure
    environment:
      NODE_ENV: development
    ports:
      - '3000:3000'
    depends_on:
      - db-dev
      # - mongo-dev
    volumes:
      - ./var/www/html/images:/var/www/html/images
      - ./server:/server
      - /server/node_modules

  # mongo-dev:
  #   image: mongo:4.4-focal
  #   ports:
  #     - '27017:27017'

  db-dev:
    image: postgres:13-alpine
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=todo-dev
    ports:
      - '5432:5432'

volumes:
  server-dev:
