import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import { ReduxProvider } from 'store/providers';
import './globals.css';
import { Toast } from 'components/general';

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  manifest: '/manifest.json',
  other: { 'theme-color': '#000000' },
};

type Props = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: Props) {
  return (
    <ReduxProvider>
      <html lang="en">
        <body className={poppins.className}>
          <Toast>{children}</Toast>
        </body>
      </html>
    </ReduxProvider>
  );
}
