import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import type { FC, PropsWithChildren } from 'react';
import { Toast } from 'components/general';
import { ReduxProvider } from 'store/providers';
import './globals.css';

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  manifest: '/manifest.json',
  other: { 'theme-color': '#000000' },
} satisfies Metadata;

const RootLayout = (({ children }) => (
  <ReduxProvider>
    <html lang="en">
      <body className={poppins.className}>
        <Toast>{children}</Toast>
      </body>
    </html>
  </ReduxProvider>
)) satisfies FC<PropsWithChildren>;

export default RootLayout;
